### ISSUE TITLE
Read MAC address

### ISSUE THREAD

**Issue by jampcri** [Servoy/svyPhonegap#1]
Hello
It´s possible a web component for read MAC address in mobile phone or tablet.
Thanks.

**Comment by tuanway** [comment]
You can try one of the phonegap plugins available.

https://github.com/mohamed-salah/MacAddress
https://www.npmjs.com/package/u cordova-plugin-ip-mac-address

**Comment by jampcri** [comment]
Yes taht I know, but I don't know how read that information on Servoy
Thanks

**Comment by jurraburusvy** [comment]
With the new getDeviceInfo that has been added yesterday you will be able to get the version, platform, model and uuid of the device.

**Comment by pruhsert** [comment]
I don't think you can get access to the Mac address. The uuid of the device is your best shot, but be aware that at least on iOS it's not really the uuid of the device, but a uuid that phoneGap generates when the app is first started. Access to the device ID has been removed by Apple a few years ago. That means that after a user deletes and reinstalls the app, it will have changed.

**Comment by jampcri** [comment]
I need make an identification of the device. For example, through a script in Phonegap, I can read the serial of the device, that´s enough for the device identification.

**Comment by pruhsert** [comment]
> I can read the serial of the device

... not that I know of. As mentioned before, device.uuid is your best shot (I think), unless your identifier needs to survive deletion and re-installation of the app. There is yet another phonegap plugin that can store a uuid somewhere that supposedly will even survive that, but I have never tried that one.

**Comment by jurraburusvy** [comment]
Yes we are using uuid for that. 

Juan Manuel Urraburu

**Comment by jampcri** [comment]
Actually, when Open app, I have that information from the device:

> Device Model: WAS-LX1A

> Device Cordova: 6.4.0

> Device Platform: Android

> Device UUID: 2cdf5bcf1db65fd7

> Device Version: 7.0

> Device Serial: 2XJ4C17323001498

This information is enough for identify the device.
I pass the serial number and platform by arguments in url  that call to the application in Servoy .

**Comment by jurraburusvy** [comment]
Where do you get that info from?

Juan Manuel Urraburu

**Comment by pruhsert** [comment]
Again, I wouldn't rely on that. Try that on iOS or another Android device and you might not see a device serial there...

**Comment by pruhsert** [comment]
> Where do you get that info from?

That is just output of the properties of the device object...

**Comment by tuanway** [comment]
@pruhsert You are correct about this not working on new IOS devices.  
https://github.com/mohamed-salah/MacAddress/issues/15

@jampcri What's the goal of having a unique identifier?  Is it more so to help debug issues with a particular device or something more? You could consider storing their (login + useragent + screen width/height) as an unique identifier.

**Comment by jampcri** [comment]
I probe it in an Ipad and I don´t have the serial number:

> Devide Model: iPad4,1

> Device Cordova: 4.1.1

> Device Platform: iOS

> Device UUID:D7B610F5-ABEE-479C-9E78-5FE42066257F

> Device Version: 9.3.2

> Devide Serial: unknown

You are right.

@tuanway login+useragent+model+....... can be an option

**Comment by jurraburusvy** [comment]
Hi Tuan,
In our case is to avoid asking for login each time. When it starts we check and if we have that uuid registered, we assume who the user is and avoid the login screen.
Regards,
Juan Manuel Urraburu 
 

----------------------- Original Message -----------------------

**Comment by pruhsert** [comment]
> login+useragent+model+....... can be an option

You don’t like UUIDs, do you?

**Comment by jampcri** [comment]
No, I like them if not change

**Comment by jcompagner** [comment]
> Hi Tuan, In our case is to avoid asking for login each time. When it starts we check and if we have that uuid registered, we assume who the user is and avoid the login screen. Regards, Juan Manuel Urraburu  

aren't there access tokens used for?

So the users logs in once and you generate then a access token (which can be just a uuid) and as long as he sends that access token he can login with that? And maybe have on the backend a revoke for a specific token?

**Comment by tuanway** [comment]
@jcompagner 
Agreed. Access tokens are the way to go if they aren't being used already.

If you need to identify a device/user you can store all the other stuff (phone model, screen width/height, login id) along side it in the back-end server.
