### ISSUE TITLE
PhoneGap camera restarts the application

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyPhonegap#15]
Hi,
using the servoy app I have done some test with the different phonegab plugins but I have problems with the camera plugin.
It launch the camera correctly, if I click to cancel, return perfect to the app, but If I make a photo with the camera and click OK to the photo the app restart.

This is the test that I use:
`function phonegapTestGetPicture(){
	var options = {
		  quality: 50,
		  destinationType: 0,
		  sourceType: 1,
		  correctOrientation: true
		}
	if (plugins.svyphonegapCamera.isSupported(honegabTestGetPictureIsSupportedcallbackMethod)){
		plugins.svyphonegapCamera.getPicture(phonegapTestGetPictureGetPicSuccess, phonegapTestGetPictureGetPicFail,options);	
	}
	else scopes.utl_dialog.utl_dialog_warning('svyphonegapCamera No Supported');
}
`

My device info: 
         cordova:"8.0.0",
         model:"Mi A2 Lite",
        platform:"Android",uuid:"7c3bd8ca939517ba",
        version:"10

I found some links that talk about that.
[https://stackoverflow.com/questions/8368091/phonegap-camera-restarts-the-application](url)
[https://github.com/apache/cordova-plugin-camera/issues/660](url)
[https://github.com/apache/cordova-plugin-camera/issues/611](url)

Un Saludo

Juan Ramírez

**Comment by tuanway** [comment]
Consider using the camera preview plugin.  It's a new plugin that if used will not require you to move away from the application.  That might help for this scenario
