### ISSUE TITLE
Application needs to be updated

### ISSUE THREAD

**Issue by jampcri** [Servoy/svyPhonegap#16]
I'm making an App for IOS whit the Servoy Mobile Build generator and I have This error when I try open the App in the Iphone
"Application needs to be updated"

I use the last version of the Mac, then I think the problem is in the Servoy Mobile Build generator

Thanks

**Comment by tuanway** [comment]
We will probably need a bit more detail. Your application was working at some point right?
Did you update to the latest IOS version? if so what version is that?
When was the last time you built with the cloud builder? You may need to generate a new build.

**Comment by jampcri** [comment]
Hi

 

It is the first time that I generate an app for ios

The application it’s wordking fine in Android and of course in Windows NG and Smart

I have created the certificates with a not very new version of IOS (High Sierra 10.13.6)

Run the Servoy Mobile build generator on a Mac with the latest version updated over the weekend

If you need it, I can send you the certificates and the password

 

Thanks

 

 

 

De: Tuan Nguyen ***@***.***> 
Enviado el: lunes, 13 de junio de 2022 16:43
Para: Servoy/svyPhonegap ***@***.***>
CC: jampcri ***@***.***>; Author ***@***.***>
Asunto: Re: [Servoy/svyPhonegap] Application needs to be updated (Issue #16)

 

We will probably need a bit more detail. Your application was working at some point right?
Did you update to the latest IOS version? if so what version is that?
When was the last time you built with the cloud builder? You may need to generate a new build.

**Comment by tuanway** [comment]
The mobile builder is meant for IOS devices, (such as an iPhone or iPad). Are you looking for a desktop app builder for the Mac OS?

The version you specified is for a Mac machine (i.e desktop or laptop computer) not an IOS device.

Please be clear about the device you are running this on.

**Comment by jampcri** [comment]
Yes, I need create an app for Iphone

 

I use Servoy Mobile Build Generator in Mac for create the files for APP

 

Thanks

 

De: Tuan Nguyen ***@***.***> 
Enviado el: martes, 14 de junio de 2022 16:30
Para: Servoy/svyPhonegap ***@***.***>
CC: jampcri ***@***.***>; Author ***@***.***>
Asunto: Re: [Servoy/svyPhonegap] Application needs to be updated (Issue #16)

 

The mobile builder is meant for IOS devices, (such as an iPhone or iPad). Are you looking for a desktop app builder for the Mac OS?

The version you specified is for a Mac machine (i.e desktop or laptop computer) not an IOS device.

Please be clear about the device you are running this on.

**Comment by tuanway** [comment]
Ok. Please include the IOS version that the iPhone is running. Also please include the settings used for the builder , maybe a screenshot ?

I'm closing this ticket now until that information is provided.

**Comment by jampcri** [comment]
Maybe the problem is the version of servoy I'm using  Servoy 2021.03.0

????

 

Thanks

 

 

De: Tuan Nguyen ***@***.***> 
Enviado el: martes, 14 de junio de 2022 19:06
Para: Servoy/svyPhonegap ***@***.***>
CC: jampcri ***@***.***>; Author ***@***.***>
Asunto: Re: [Servoy/svyPhonegap] Application needs to be updated (Issue #16)

 

Ok. Please include the IOS version that the iPhone is running. Also please include the settings used for the builder , maybe a screenshot ?

I'm closing this ticket now until that information is provided.
