### ISSUE TITLE
svyphonegapBarcode

### ISSUE THREAD

**Issue by jampcri** [Servoy/svyPhonegap#17]
Hi
I use Servoy 2022.09.2 and I have this error when scan a code bar

ERROR org.sablo.BrowserConsole - Error scanning barcode: cordova is not defined

Thanks

**Comment by paronne** [comment]
Hi,

looks like phonegap is not initialized.
have you build the application into an Android .apk or iOS .ipa installer and inizialied the phonegap module as descibed in the wiki ? see https://github.com/Servoy/svyPhonegap/wiki

Regards,
Paolo

**Comment by jampcri** [comment]
Yes, I have.
The camera woks fine

**Comment by tuanway** [comment]
@jampcri Are you using the mobile builder? Which plugins did you select?

**Comment by jampcri** [comment]
Hi
It's working

Thanks
