### ISSUE TITLE
Missing purpose string in Info.plist 

### ISSUE THREAD

**Issue by vision-developer** [Servoy/svyPhonegap#18]
I have created a new version of our app with your build tool, but it is rejected by Apple appstore (see info below). A string is missing in the info.plist file.

_Dear Developer, 

We identified one or more issues with a recent delivery for your app, "E-Vision Mobile" 1.9.0 (1.9.0). Your delivery was successful, but you may wish to correct the following issues in your next delivery: ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “E-Vision Mobile.app” bundle should contain a NSLocationAlwaysAndWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources. 

After you’ve corrected the issues, you can upload a new binary to App Store Connect. 

Best regards, 

The App Store Team_

**Comment by tuanway** [comment]
Hi, are you selecting the location plugin when generating a build?

**Comment by vision-developer** [comment]
Yes, for picking the current location of a project.

**Comment by tuanway** [comment]
Can you share a screenshot of your configuration?

Also generate a new binary, and I'll review.

**Comment by vision-developer** [comment]
![image](https://github.com/Servoy/svyPhonegap/assets/140624726/ffeb9d04-7265-46d6-9746-9e1fabe48d7d)

**Comment by vision-developer** [comment]
![image](https://github.com/Servoy/svyPhonegap/assets/140624726/5932e8df-74f0-410a-9419-e0e6ce74b57f)

**Comment by vision-developer** [comment]
![image](https://github.com/Servoy/svyPhonegap/assets/140624726/5685408f-0711-4879-8063-ded1ac8f4f0e)

**Comment by vision-developer** [comment]
![image](https://github.com/Servoy/svyPhonegap/assets/140624726/99761c01-bebe-4fad-93b5-f98d09b2deaa)

**Comment by tuanway** [comment]
OK. I see the issue. I'll try to resolve in a bit here.

**Comment by vision-developer** [comment]
Great!

**Comment by tuanway** [comment]
I've updated the builder code.  Can you try to generate a new binary?  It should have that flag set now in the info.plist.

**Comment by vision-developer** [comment]
Is building now...

**Comment by vision-developer** [comment]
I wll upload this ipa to the app store, and will let you know if succesfull.

**Comment by vision-developer** [comment]
I think the Info.plist is now ok, but I have another when the app is started on my Ipad.

![image](https://github.com/Servoy/svyPhonegap/assets/140624726/fb5cf44a-459d-4ab8-8b79-588e0457689f)

**Comment by tuanway** [comment]
Which version of the module are you using?  There was a bug for this issue that was resolve in v1.1.7.

I'm going to close this specific issue and you can open a different one if the latest version is still an problem.

**Comment by vision-developer** [comment]
_Which version of the module are you using? There was a bug for this issue that was resolve in v1.1.7._

The issue was fixed in versie 1.1.0 and that version is still the one we are using.

**Comment by tuanway** [comment]
no, that still way too old of a version to use.  You will have better luck with the latest.  There's also other bugs that 1.1.0 have.  You should update to the latest.

**Comment by vision-developer** [comment]
I have tried importing the 1.1.9 version, but I got an error on our Servoy 2020.3.3.3565_LTS version.
![image](https://github.com/Servoy/svyPhonegap/assets/140624726/3c7e65b0-87ff-484b-9731-0cf634a2c863)

**Comment by tuanway** [comment]
You can try importing the project from source code.  Just download and import the project.  
Otherwise you can try installing a newer version of Servoy.
