### ISSUE TITLE
Error in Google Play Console

### ISSUE THREAD

**Issue by vision-developer** [Servoy/svyPhonegap#19]
When I upload the build to the Google Play Console I get an Error.

![image](https://github.com/Servoy/svyPhonegap/assets/140624726/c1d06808-7c67-418e-ae51-ce46ae39340b)

The translation to English is : You cannot deploy this release because the release does not allow existing users to upgrade to the recently added app bundles.

**Comment by tuanway** [comment]
Hi, When building the binary are you incrementing the "App Version"? I think that you might get this message if you are trying to roll out a release on an older version number.  Please double check.

**Comment by vision-developer** [comment]
I have created a new binary with the same app version, and now it is accepted by Google. I don't know for sure what I did wrong, but it could be that I forgot to check the Clear Text plugin.
