### ISSUE TITLE
Mobile Build Generator

### ISSUE THREAD

**Issue by JAMPCR** [Servoy/svyPhonegap#20]
Hi

Now you cannot generate an apk through the Mobile Build Generator.
What are the steps now to generate an app?

Thanks

**Comment by tuanway** [comment]
Check out the wiki
https://github.com/Servoy/svyPhonegap/wiki

You need to sign up for a servoy cloud account, and you can make a free build through there.

**Comment by JAMPCR** [comment]
Since yesterday morning he tells me that he is creating space. Is it normal for so long?
![Captura](https://github.com/Servoy/svyPhonegap/assets/132928111/337c6a8e-77a4-433c-989d-5dbb49a68813)

**Comment by RvVeen** [comment]
Hi @JAMPCR,

It seems like something is hanging during the automated process. 
Could you please log in again and verify if it is still busy with the setup? 
If that is indeed the case, please create a support ticket by logging in and clicking on the username (top right), then selecting "Support Ticket."

https://docs.servoy.com/reference/servoy-cloud/cloud-control-center/user-profile/support
