### ISSUE TITLE
Error Code 20 on Android Camera

### ISSUE THREAD

**Issue by vision-developer** [Servoy/svyPhonegap#22]
When opening the camera I get error 20 on Android devices. Seems this is since the update to API level 33.

See https://github.com/apache/cordova-plugin-camera/issues/826

**Comment by tuanway** [comment]
This should be fixed in the latest build in cloud control center.  Try creating a new build from there.

**Comment by vision-developer** [comment]
Hi Tuan,

 

I get an error when i try to add our application in the cloud center. 

 

What can I do?

 

Regards,

 

Nic

 

 



 

Van: Tuan Nguyen ***@***.***> 
Verzonden: vrijdag 20 oktober 2023 14:26
Aan: Servoy/svyPhonegap ***@***.***>
CC: Nic van Dijk ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Servoy/svyPhonegap] Error Code 20 on Android Camera (Issue #22)

 

This should be fixed in the latest build in cloud control center. Try creating a new build from there.

**Comment by vision-developer** [comment]
Hi, Tuan,

Discard previous mail. 

I will contact Rene van Veen for information about Servoy's cloud control center. I need to have information about how to creat a binary from there.

Regards,

Nic
