### ISSUE TITLE
onReadyCallback is not executed on IOS devices

### ISSUE THREAD

**Issue by vision-developer** [Servoy/svyPhonegap#23]
I have created a new app in Servoy Cloud, but the IOS app does not execute the callback function. The Android app which was created at the same time does execute the callback function.
I have tried this on a iPhone and and iPad, but on both devices the callback is not executed.
We work with Servoy version: 2020.3.3.3565_LTS, and Phonegap version 1.2.2

![image](https://github.com/Servoy/svyPhonegap/assets/140624726/68e6a4f3-ab80-4b71-ab3b-b8be68baa15c)
![image](https://github.com/Servoy/svyPhonegap/assets/140624726/1ead26c8-a149-4ed2-856f-fce8b2adc34c)
![image](https://github.com/Servoy/svyPhonegap/assets/140624726/834aef8b-6e4d-474a-b145-54131856128d)

**Comment by tuanway** [comment]
Can you share your source code?  Create a private ticket on Jira.

**Comment by vision-developer** [comment]
I have create a ticket in Jira. https://support.servoy.com/browse/SVYX-748

**Comment by tuanway** [comment]
Closing this issue, as resolution will be within the JIRA ticket
