### ISSUE TITLE
Insufficient explanation the use of camera in info.plist file

### ISSUE THREAD

**Issue by vision-developer** [Servoy/svyPhonegap#24]
In the review for submittance in the app store there is a problem with the info.plist file:

_Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage

We noticed that your app requests the user’s consent to access the camera, but doesn’t sufficiently explain the use of the camera in the purpose string.

To help users make informed decisions about how their data is used, permission request alerts need to explain and include an example of how your app will use the requested information.

Next Steps

Please revise the purpose string in your app’s Info.plist file for the camera to explain why your app needs access and include an example of how the user's data will be used.

You can modify your app's Info.plist file using the property list editor in Xcode._

**Comment by vision-developer** [comment]
Here is the screenshot from the app.
![Screenshot-1208-110256](https://github.com/Servoy/svyPhonegap/assets/140624726/7a61ab25-b1c8-4647-b2eb-8d5809b1006a)

**Comment by tuanway** [comment]
Hi could you create a ticket via the cloud control center UI?

**Comment by tuanway** [comment]
I think we likely need to make this value be user entered in the cloud builder.  As Apple probably wants a more descriptive reason behind the use of the camera

**Comment by vision-developer** [comment]
I have created a ticket in Cloud Control Center. Where can I see a follow up now?

**Comment by tuanway** [comment]
The option to add more descriptive information is now available on the control center
