### ISSUE TITLE
Can't edit the index.html

### ISSUE THREAD

**Issue by HV-Office** [Servoy/svyPhonegap#3]
Hi there! I'm trying to work with the PhoneGap plugin but i can't change my index.html file. Every time if I start the app via browser servoy overwrites/delete the old one and creates new files. How can I change that?

> Add dist/bridge.js and dist/index.js reference to your main index.html file within the phonegap app project directory.
> <script type="text/javascript" src="js/bridge.js"></script>

I installed the PhoneGap Web Package but I can't use that either. I dont't see anything in the Palette. I only have the mobile and the dialogs plugin.

**Comment by tuanway** [comment]
Hi, can you go over the guide within wiki and try again that way?  You shouldn't have to modify any index.html files going forward.
