### ISSUE TITLE
Error to build a Phonegap application 

### ISSUE THREAD

**Issue by jampcri** [Servoy/svyPhonegap#4]
Hello
I have an error when build a Phonegap application.
If I add this line at he end of the config.xml:

`  <plugin name="cordova-plugin-fcm-with-dependecy-updated" spec="https://github.com/tuanway/cordova-plugin-fcm-with-dependecy-updated" />`

I have the attach error to build

If don´t add this line to the config xml, I can build perfectly but the options of the device dosen´t work
 
If I test it in local, with this line, the application works fine.

This is the error in log to build:

`Build Date: 2019-11-27 12:31:02 +0000
--------------------------------------------------------------------------------
PREPARE OUTPUT
--------------------------------------------------------------------------------
Generating platform-specific config.xml from defaults for android at /var/gimlet/tmp/47416961216000/3786170/res/xml/config.xml
Merging project's config.xml into platform-specific android config.xml
Merging and updating files from [www, ../platform_www] to ../assets/www
  mkdir ../assets/www/cordova-js-src
  mkdir ../assets/www/cordova-js-src/android
  copy  ../platform_www/cordova-js-src/android/nativeapiprovider.js ../assets/www/cordova-js-src/android/nativeapiprovider.js (new file)
  copy  ../platform_www/cordova-js-src/android/promptbasednativeapi.js ../assets/www/cordova-js-src/android/promptbasednativeapi.js (new file)
  copy  ../platform_www/cordova-js-src/exec.js ../assets/www/cordova-js-src/exec.js (new file)
  copy  ../platform_www/cordova-js-src/platform.js ../assets/www/cordova-js-src/platform.js (new file)
  mkdir ../assets/www/cordova-js-src/plugin
  mkdir ../assets/www/cordova-js-src/plugin/android
  copy  ../platform_www/cordova-js-src/plugin/android/app.js ../assets/www/cordova-js-src/plugin/android/app.js (new file)
  copy  ../platform_www/cordova.js ../assets/www/cordova.js (updated file)
  rmdir  ../assets/www/css (no source)
  delete ../assets/www/css/index.css (no source)
  rmdir  ../assets/www/img (no source)
  delete ../assets/www/img/cordova.png (no source)
  delete ../assets/www/img/logo.png (no source)
  copy  www/index.html ../assets/www/index.html (updated file)
  copy  www/js/bridge.js ../assets/www/js/bridge.js (new file)
  copy  www/js/index.js ../assets/www/js/index.js (updated file)
  mkdir ../assets/www/res
  copy  www/res/.pgbomit ../assets/www/res/.pgbomit (new file)
  mkdir ../assets/www/res/icon
  copy  www/res/icon.png ../assets/www/res/icon.png (new file)
  mkdir ../assets/www/res/icon/android
  copy  www/res/icon/android/drawable-hdpi-icon.png ../assets/www/res/icon/android/drawable-hdpi-icon.png (new file)
  copy  www/res/icon/android/drawable-ldpi-icon.png ../assets/www/res/icon/android/drawable-ldpi-icon.png (new file)
  copy  www/res/icon/android/drawable-mdpi-icon.png ../assets/www/res/icon/android/drawable-mdpi-icon.png (new file)
  copy  www/res/icon/android/drawable-xhdpi-icon.png ../assets/www/res/icon/android/drawable-xhdpi-icon.png (new file)
  copy  www/res/icon/android/drawable-xxhdpi-icon.png ../assets/www/res/icon/android/drawable-xxhdpi-icon.png (new file)
  copy  www/res/icon/android/drawable-xxxhdpi-icon.png ../assets/www/res/icon/android/drawable-xxxhdpi-icon.png (new file)
  copy  www/res/icon/android/icon-144-xxhdpi.png ../assets/www/res/icon/android/icon-144-xxhdpi.png (new file)
  copy  www/res/icon/android/icon-192-xxxhdpi.png ../assets/www/res/icon/android/icon-192-xxxhdpi.png (new file)
  copy  www/res/icon/android/icon-36-ldpi.png ../assets/www/res/icon/android/icon-36-ldpi.png (new file)
  copy  www/res/icon/android/icon-48-mdpi.png ../assets/www/res/icon/android/icon-48-mdpi.png (new file)
  copy  www/res/icon/android/icon-72-hdpi.png ../assets/www/res/icon/android/icon-72-hdpi.png (new file)
  copy  www/res/icon/android/icon-96-xhdpi.png ../assets/www/res/icon/android/icon-96-xhdpi.png (new file)
  copy  www/res/icon/icon.png ../assets/www/res/icon/icon.png (new file)
  mkdir ../assets/www/res/icon/ios
  copy  www/res/icon/ios/icon-40.png ../assets/www/res/icon/ios/icon-40.png (new file)
  copy  www/res/icon/ios/icon-40@2x.png ../assets/www/res/icon/ios/icon-40@2x.png (new file)
  copy  www/res/icon/ios/icon-50.png ../assets/www/res/icon/ios/icon-50.png (new file)
  copy  www/res/icon/ios/icon-50@2x.png ../assets/www/res/icon/ios/icon-50@2x.png (new file)
  copy  www/res/icon/ios/icon-57-2x.png ../assets/www/res/icon/ios/icon-57-2x.png (new file)
  copy  www/res/icon/ios/icon-57.png ../assets/www/res/icon/ios/icon-57.png (new file)
  copy  www/res/icon/ios/icon-60-3x.png ../assets/www/res/icon/ios/icon-60-3x.png (new file)
  copy  www/res/icon/ios/icon-60.png ../assets/www/res/icon/ios/icon-60.png (new file)
  copy  www/res/icon/ios/icon-60@2x.png ../assets/www/res/icon/ios/icon-60@2x.png (new file)
  copy  www/res/icon/ios/icon-60@3x.png ../assets/www/res/icon/ios/icon-60@3x.png (new file)
  copy  www/res/icon/ios/icon-70@2x.png ../assets/www/res/icon/ios/icon-70@2x.png (new file)
  copy  www/res/icon/ios/icon-72.png ../assets/www/res/icon/ios/icon-72.png (new file)
  copy  www/res/icon/ios/icon-72@2x.png ../assets/www/res/icon/ios/icon-72@2x.png (new file)
  copy  www/res/icon/ios/icon-76.png ../assets/www/res/icon/ios/icon-76.png (new file)
  copy  www/res/icon/ios/icon-76@2x.png ../assets/www/res/icon/ios/icon-76@2x.png (new file)
  copy  www/res/icon/ios/icon-80-2x.png ../assets/www/res/icon/ios/icon-80-2x.png (new file)
  copy  www/res/icon/ios/icon-80@2x.png ../assets/www/res/icon/ios/icon-80@2x.png (new file)
  copy  www/res/icon/ios/icon-small.png ../assets/www/res/icon/ios/icon-small.png (new file)
  copy  www/res/icon/ios/icon-small@2x.png ../assets/www/res/icon/ios/icon-small@2x.png (new file)
  copy  www/res/icon/ios/icon-small@3x.png ../assets/www/res/icon/ios/icon-small@3x.png (new file)
  copy  www/res/icon/ios/icon.png ../assets/www/res/icon/ios/icon.png (new file)
  copy  www/res/icon/ios/icon@2x.png ../assets/www/res/icon/ios/icon@2x.png (new file)
  copy  www/res/iconnotrans.jpeg ../assets/www/res/iconnotrans.jpeg (new file)
  mkdir ../assets/www/res/screen
  mkdir ../assets/www/res/screen/android
  copy  www/res/screen/android/drawable-land-hdpi-screen.png ../assets/www/res/screen/android/drawable-land-hdpi-screen.png (new file)
  copy  www/res/screen/android/drawable-land-ldpi-screen.png ../assets/www/res/screen/android/drawable-land-ldpi-screen.png (new file)
  copy  www/res/screen/android/drawable-land-mdpi-screen.png ../assets/www/res/screen/android/drawable-land-mdpi-screen.png (new file)
  copy  www/res/screen/android/drawable-land-xhdpi-screen.png ../assets/www/res/screen/android/drawable-land-xhdpi-screen.png (new file)
  copy  www/res/screen/android/drawable-land-xxhdpi-screen.png ../assets/www/res/screen/android/drawable-land-xxhdpi-screen.png (new file)
  copy  www/res/screen/android/drawable-land-xxxhdpi-screen.png ../assets/www/res/screen/android/drawable-land-xxxhdpi-screen.png (new file)
  copy  www/res/screen/android/drawable-port-hdpi-screen.png ../assets/www/res/screen/android/drawable-port-hdpi-screen.png (new file)
  copy  www/res/screen/android/drawable-port-ldpi-screen.png ../assets/www/res/screen/android/drawable-port-ldpi-screen.png (new file)
  copy  www/res/screen/android/drawable-port-mdpi-screen.png ../assets/www/res/screen/android/drawable-port-mdpi-screen.png (new file)
  copy  www/res/screen/android/drawable-port-xhdpi-screen.png ../assets/www/res/screen/android/drawable-port-xhdpi-screen.png (new file)
  copy  www/res/screen/android/drawable-port-xxhdpi-screen.png ../assets/www/res/screen/android/drawable-port-xxhdpi-screen.png (new file)
  copy  www/res/screen/android/drawable-port-xxxhdpi-screen.png ../assets/www/res/screen/android/drawable-port-xxxhdpi-screen.png (new file)
  mkdir ../assets/www/res/screen/ios
  copy  www/res/screen/ios/Default-568h@2x~iphone.png ../assets/www/res/screen/ios/Default-568h@2x~iphone.png (new file)
  copy  www/res/screen/ios/Default-667h.png ../assets/www/res/screen/ios/Default-667h.png (new file)
  copy  www/res/screen/ios/Default-736h.png ../assets/www/res/screen/ios/Default-736h.png (new file)
  copy  www/res/screen/ios/Default-Landscape-736h.png ../assets/www/res/screen/ios/Default-Landscape-736h.png (new file)
  copy  www/res/screen/ios/Default-Landscape@2x~ipad.png ../assets/www/res/screen/ios/Default-Landscape@2x~ipad.png (new file)
  copy  www/res/screen/ios/Default-Landscape~ipad.png ../assets/www/res/screen/ios/Default-Landscape~ipad.png (new file)
  copy  www/res/screen/ios/Default-Portrait@2x~ipad.png ../assets/www/res/screen/ios/Default-Portrait@2x~ipad.png (new file)
  copy  www/res/screen/ios/Default-Portrait~ipad.png ../assets/www/res/screen/ios/Default-Portrait~ipad.png (new file)
  copy  www/res/screen/ios/Default@2x~iphone.png ../assets/www/res/screen/ios/Default@2x~iphone.png (new file)
  copy  www/res/screen/ios/Default~iphone.png ../assets/www/res/screen/ios/Default~iphone.png (new file)
  copy  www/res/splash.png ../assets/www/res/splash.png (new file)
Wrote out android application name "PhoneGap Example" to /var/gimlet/tmp/47416961216000/3786170/res/values/strings.xml
android-versionCode not found in config.xml. Generating a code based on version in config.xml (1.0.0): 10000
Wrote out Android package name "com.phonegap.example" to /var/gimlet/tmp/47416961216000/3786170/src/com/phonegap/example/PhoneGapExample.java
Updating icons at ../res
  copy  www/res/icon/android/drawable-hdpi-icon.png ../res/mipmap-hdpi/icon.png (new file)
  copy  www/res/icon/android/drawable-ldpi-icon.png ../res/mipmap-ldpi/icon.png (new file)
  copy  www/res/icon/android/drawable-mdpi-icon.png ../res/mipmap-mdpi/icon.png (new file)
  copy  www/res/icon/android/drawable-xhdpi-icon.png ../res/mipmap-xhdpi/icon.png (new file)
  copy  www/res/icon/android/drawable-xxhdpi-icon.png ../res/mipmap-xxhdpi/icon.png (new file)
  copy  www/res/icon/android/drawable-xxxhdpi-icon.png ../res/mipmap-xxxhdpi/icon.png (new file)
Updating splash screens at ../res
  copy  www/res/screen/android/drawable-land-hdpi-screen.png ../res/drawable-land-hdpi/screen.png (new file)
  copy  www/res/screen/android/drawable-land-ldpi-screen.png ../res/drawable-land-ldpi/screen.png (new file)
  copy  www/res/screen/android/drawable-land-mdpi-screen.png ../res/drawable-land-mdpi/screen.png (new file)
  copy  www/res/screen/android/drawable-land-xhdpi-screen.png ../res/drawable-land-xhdpi/screen.png (new file)
  copy  www/res/screen/android/drawable-land-xxhdpi-screen.png ../res/drawable-land-xxhdpi/screen.png (new file)
  copy  www/res/screen/android/drawable-land-xxxhdpi-screen.png ../res/drawable-land-xxxhdpi/screen.png (new file)
  copy  www/res/screen/android/drawable-port-hdpi-screen.png ../res/drawable-port-hdpi/screen.png (new file)
  copy  www/res/screen/android/drawable-port-ldpi-screen.png ../res/drawable-port-ldpi/screen.png (new file)
  copy  www/res/screen/android/drawable-port-mdpi-screen.png ../res/drawable-port-mdpi/screen.png (new file)
  copy  www/res/screen/android/drawable-port-xhdpi-screen.png ../res/drawable-port-xhdpi/screen.png (new file)
  copy  www/res/screen/android/drawable-port-xxhdpi-screen.png ../res/drawable-port-xxhdpi/screen.png (new file)
  copy  www/res/screen/android/drawable-port-xxxhdpi-screen.png ../res/drawable-port-xxxhdpi/screen.png (new file)
Updating resource files at ..
  copy  google-services.json ../google-services.json (new file)
Prepared android project successfully
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-statusbar@^2.4.2" via npm
Installing "cordova-plugin-statusbar" at "2.4.3" for android
Fetching plugin "cordova-plugin-whitelist@^1.3.3" via npm
Installing "cordova-plugin-whitelist" at "1.3.4" for android
Fetching plugin "cordova-plugin-camera@^2.4.1" via npm
Installing "cordova-plugin-camera" at "2.4.1" for android
Fetching plugin "cordova-plugin-compat@^1.1.0" via npm
Installing "cordova-plugin-compat" at "1.2.0" for android
Subproject Path: CordovaLib
Fetching plugin "cordova-plugin-network-information@^1.3.4" via npm
Installing "cordova-plugin-network-information" at "1.3.4" for android
Fetching plugin "cordova-plugin-networkinterface@^2.0.0" via npm
Installing "cordova-plugin-networkinterface" at "2.0.0" for android
Fetching plugin "cordova-plugin-geolocation@^2.4.3" via npm
Installing "cordova-plugin-geolocation" at "2.4.3" for android
Plugin dependency "cordova-plugin-compat@1.2.0" already fetched, using that version.
Dependent plugin "cordova-plugin-compat" already installed on android.
Fetching plugin "cordova-plugin-file@^4.3.3" via npm
Installing "cordova-plugin-file" at "4.3.3" for android
Plugin dependency "cordova-plugin-compat@1.2.0" already fetched, using that version.
Dependent plugin "cordova-plugin-compat" already installed on android.

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
b3476bfee46dcacfbe48e98b1f347f254894215b
Fetching plugin "https://github.com/tuanway/cordova-ios-fullscreen" via git clone
Using shallow clone
Repository "https://github.com/tuanway/cordova-ios-fullscreen" checked out to git ref "master" at "b3476bf".
Installing "it.innowatio.cordova.ios-fullscreen" at "0.3.0" for android
Fetching plugin "cordova-plugin-inappbrowser@^1.7.2" via npm
Installing "cordova-plugin-inappbrowser" at "1.7.2" for android
Fetching plugin "cordova-plugin-device@^1.1.7" via npm
Installing "cordova-plugin-device" at "1.1.7" for android
Fetching plugin "cordova-plugin-fingerprint-aio@^1.6.0" via npm
Installing "cordova-plugin-fingerprint-aio" at "1.7.0" for android
d39bba6cc94573411ab043d75bde4724a6f9c356
Fetching plugin "https://github.com/tuanway/cordova-plugin-fcm-with-dependecy-updated" via git clone
Using shallow clone
Repository "https://github.com/tuanway/cordova-plugin-fcm-with-dependecy-updated" checked out to git ref "master" at "d39bba6".
Installing "cordova-plugin-fcm-with-dependecy-updated" at "2.4.0" for android
Subproject Path: CordovaLib

WARNING: Overriding compileSdkVersion from android-25 (default) to android-26
WARNING: This is unsupported, please consider updating your phonegap version instead
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:24.1.1+
cordova.system.library.2=com.google.firebase:firebase-core:10.+
cordova.system.library.3=com.google.firebase:firebase-messaging:10.+
cordova.gradle.include.1=cordova-plugin-fcm-with-dependecy-updated/example-FCMPlugin.gradle
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_f3waqmdr9m0efuir5txy5o1yg.run(/var/gimlet/tmp/47416961216000/3786170/build.gradle:157)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Could not find google-services.json while looking in [src/debug]
Could not find google-services.json while looking in [src/release]
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportCompat2520Library
:prepareComAndroidSupportSupportCoreUi2520Library
:prepareComAndroidSupportSupportCoreUtils2520Library
:prepareComAndroidSupportSupportFragment2520Library
:prepareComAndroidSupportSupportMediaCompat2520Library
:prepareComAndroidSupportSupportV42520Library
:prepareComGoogleAndroidGmsPlayServicesBasement1026Library
:prepareComGoogleAndroidGmsPlayServicesTasks1026Library
:prepareComGoogleFirebaseFirebaseAnalytics1026Library
:prepareComGoogleFirebaseFirebaseAnalyticsImpl1026Library
:prepareComGoogleFirebaseFirebaseCommon1026Library
:prepareComGoogleFirebaseFirebaseCore1026Library
:prepareComGoogleFirebaseFirebaseIid1026Library
:prepareComGoogleFirebaseFirebaseMessaging1026Library
:prepareOrgApacheCordovaCordovaLib623DebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:processDebugGoogleServices
Parsing json file: /var/gimlet/tmp/47416961216000/3786170/google-services.json
:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 11

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.838 secs
Error: /var/gimlet/tmp/47416961216000/3786170/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 11

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/var/gimlet/tmp/47416961216000/3786170/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)`

**Comment by tuanway** [comment]
Hi, How are you building the app?
Are you using the phonegap builder as shown in wiki?

**Comment by jampcri** [comment]
Hi, yes of course, I use Phonegap Builder and I have the error I've shown you.

The problem only appears to build application and the problem is the line:
`<plugin name="cordova-plugin-fcm-with-dependecy-updated" spec="https://github.com/tuanway/cordova-plugin-fcm-with-dependecy-updated" />`

Thanks

**Comment by tuanway** [comment]
![image](https://user-images.githubusercontent.com/7150474/69763369-94c1fe80-1132-11ea-8cf8-57f3c4fc58d3.png)

Now that particular plugin is used for push messaging.  Did you provide the proper google-services.json and googleService-info.plist for Android/IOS ?

**Comment by jampcri** [comment]
Hi.

I think there is a problem with tne new phonegap web component.
With the old web component version:

![image](https://user-images.githubusercontent.com/36368375/69864248-68bf8e00-1296-11ea-99aa-823002f1bd96.png)

All works fine, but with the new version in the same application

![image](https://user-images.githubusercontent.com/36368375/69864430-cbb12500-1296-11ea-8b8f-bd8b4fe656df.png)

Dosen´t works, or at least the camera option that i'm just testing

**Comment by jampcri** [comment]
Hi.

Sorry, It was my mistake

Now it´s working

Thanks
