### ISSUE TITLE
App dosen´t work in Samsung

### ISSUE THREAD

**Issue by jampcri** [Servoy/svyPhonegap#5]
Hi,
My Android App works in all mobiles but not in Samsung.

I have tried on several samsung and always the same error.

Attach image.
![Captura](https://user-images.githubusercontent.com/36368375/70897302-3d54d700-1fea-11ea-81be-575de52f1bba.JPG)

**Comment by tuanway** [comment]
For newer versions of Android,  cleartext or unsecured http calls are disabled by default.
I've created a new release to allow this, but I would suggest moving to an https secured host moving forward.

For the meantime please re-export a new apk from the phonegap builder.
